name: Parse TAO Cost

on:
  schedule:
    # cron: '*/5 * * * *'      # каждые 5 минут
  workflow_dispatch:           # ручной запуск

jobs:
  build-and-parse:
    runs-on: ubuntu-latest
    steps:
      # 1) Клонируем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Устанавливаем Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3) Виртуальное окружение и установка зависимостей
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      # 4) Пишем ключ сервис-аккаунта в файл
      - name: Write service-account key to key.json
        run: echo "$GOOGLE_KEY_JSON" > key.json
        env:
          GOOGLE_KEY_JSON: ${{ secrets.GOOGLE_KEY_JSON }}

      # 5) Делаем run.sh исполняемым (на всякий случай)
      - name: Make run.sh executable
        run: chmod +x run.sh

      # 6) Запускаем парсер
      - name: Run parser
        run: |
          source venv/bin/activate
          bash run.sh
        env:
          GOOGLE_KEY_JSON: ${{ secrets.GOOGLE_KEY_JSON }}
          SPREADSHEET_ID:  ${{ secrets.SPREADSHEET_ID }}
          SHEET_NAME:      ${{ secrets.SHEET_NAME }}
          TARGET_CELL:     ${{ secrets.TARGET_CELL }}
          SOURCE_URL:      ${{ secrets.SOURCE_URL }}
          PRICE_REGEX:     ${{ secrets.PRICE_REGEX }}
